{% set name = "root_numpy" %}
{% set version = "4.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5842bbcde92133f60a61f56e9f0a875a0dbc2a567cc65a9ac141ecd72e416878
  patches:
    - 396.patch

build:
  number: 12
  skip: true  # [win]
  # -Wno-register is required for Python 2.7 in C++17 mode
  # See: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=231073
  script: CFLAGS="${CFLAGS} -Wno-register" {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - numpy
    - pip
    - python
    - root_base
    - root-binaries
    - setuptools
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - setuptools
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  imports:
    - root_numpy
  requires:
    - nose
    - pip
  commands:
    - nosetests -s -v {{ name }} --exclude='(test_evaluate_func|test_tmva_multiclass)'
    - pip check

about:
  home: http://scikit-hep.org/root_numpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: http://scikit-hep.org/root_numpy
  dev_url: https://github.com/scikit-hep/root_numpy
  summary: The interface between ROOT and NumPy
  description: |
    root_numpy is a Python extension module that provides an efficient
    interface between ROOT and NumPy. root_numpy's internals are compiled
    C++ and can therefore handle large amounts of data much faster than
    equivalent pure Python implementations.

extra:
  recipe-maintainers:
    - chrisburr
    - duncanmmacleod
