{% set name = "root_numpy" %}
{% set version = "4.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5842bbcde92133f60a61f56e9f0a875a0dbc2a567cc65a9ac141ecd72e416878
  patches:
    - Use-1z-instead-of-17.patch  # [osx]

build:
  number: 2
  skip: true  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - root
    - numpy
  run:
    - python
    - root
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - root_numpy
  requires:
    - nose
  commands:
    - nosetests -s -v {{ name }} --exclude='(test_evaluate_func|test_tmva_multiclass)'

about:
  home: http://scikit-hep.org/root_numpy
  license: BSD
  license_family: BSD
  license_file: LICENSE
  doc_url: http://scikit-hep.org/root_numpy
  dev_url: https://github.com/scikit-hep/root_numpy
  summary: The interface between ROOT and NumPy
  description: |
    root_numpy is a Python extension module that provides an efficient
    interface between ROOT and NumPy. root_numpy's internals are compiled
    C++ and can therefore handle large amounts of data much faster than
    equivalent pure Python implementations.

extra:
  recipe-maintainers:
    - duncanmmacleod
