travis:
  secure:
    BINSTAR_TOKEN: UJEgk8KgpwNORoPI08ey5vuQJcVzCKVvVVy3TUErycJeS3dpNOpVEB3Th490AJ7E3LTdtrl78zqk5XF94wY+p4sGkVZL7sp/FGQW7tYuAtoq5YPr0M/6uDQ1ZC1fvNb/+q+Rv67Xr8oE6Q4dQfCKlMiaSpXiNZh0JwUWz4zORESf6lcUuWWO5Hj0udB5zBcA++cFVUaSYHjX/hm0HPm7nFbBPqBWJ2Vlc3q26V+fLqwgvOpLfj0XOVzrwW1IuCkek7qhphaN0UlhHD8uLQwY0/NHQ6aBcM5EU5gd8BpcYSqoS8wg97ok3Z2BDOmGTAuEada5zenYI9iqKhECowk5HQSjvBFZZNIJ5Vpl2eROc1tOwgqJzPDRj8iONGWte9IQvdxvWJRnV+d7LNDm0fuUVNfy/sGcUw9Idnfq0DBy6385M4geoHoAYODo7ZnGF28le4nZOMCzDA2eBq/eCaQPcVCnMUTFWKVvIPnGfjoZ3WEiUSNLU0h4xVusHYXRoyf0XYfY4KuF3YkcXal2Gh1v/7zvaWczYXM2e8ZneYl+MMKEbO5RUWL7pUcRDcUkn5ANVnPMS8AKWxzzRE6FRkYB2Bnb4bg0wKaD5DwRZrmETe6jLtjdk12lAtMGhUoQpd8/AIQ9Y18nNylpRTX+jXXA/wZR7xcz3eFtSK+NsRg2xF8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
